package ServletSignup;
// Generated Apr 4, 2022 11:22:45 AM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private long number;
     private String password;

    public Login() {
    }

	
    public Login(long number) {
        this.number = number;
    }
    public Login(long number, String password) {
       this.number = number;
       this.password = password;
    }
   
    public long getNumber() {
        return this.number;
    }
    
    public void setNumber(long number) {
        this.number = number;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


