package ServletSignup;
// Generated Apr 4, 2022 11:22:45 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Signup generated by hbm2java
 */
public class Signup  implements java.io.Serializable {


     private long number;
     private String firstname;
     private String middle;
     private String lastname;
     private Date dob;
     private String country;
     private Integer countrycode;
     private String gender;
     private String quote;
     private String cover;
     private String profile;
     
     
    public Signup() {
    }

	
    public Signup(long number) {
        this.number = number;
    }
    public Signup(long number, String firstname, String middle, String lastname, Date dob, String country, Integer countrycode, String gender, String quote, String cover,String profile) {
       this.number = number;
       this.firstname = firstname;
       this.middle = middle;
       this.lastname = lastname;
       this.dob = dob;
       this.country = country;
       this.countrycode = countrycode;
       this.gender = gender;
       this.quote = quote;
       this.cover = cover;       
       this.profile = profile;    
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getProfile() {
        return profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }
   
    public long getNumber() {
        return this.number;
    }
    
    public void setNumber(long number) {
        this.number = number;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getMiddle() {
        return this.middle;
    }
    
    public void setMiddle(String middle) {
        this.middle = middle;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(Integer countrycode) {
        this.countrycode = countrycode;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getQuote() {
        return this.quote;
    }
    
    public void setQuote(String quote) {
        this.quote = quote;
    }




}


